
.PHONY: default clean

ROLLUP := rollup/run.sh

OUTPUT_DIR ?= pages

TARGETS := $(patsubst src/apps/%/index.js,$(OUTPUT_DIR)/%/index.js,$(wildcard src/apps/*/index.js))


default: $(TARGETS)

$(OUTPUT_DIR)/%/index.js: src/apps/%/
	@mkdir -p $(dir $@)
	$(ROLLUP) $(wildcard $(dir $<)*) > "$@"

clean:
	rm --verbose --recursive --force $(OUTPUT_DIR)/*/*.js

